### ISSUE TITLE
Flannel layer not properly indicating when the subnet has changed

### ISSUE THREAD

**Issue by lazypower** [juju-solutions/charm-flannel#14]
As flannel leases expire and new leases emerge, it becomes important to signal to consuming layers this has happened.

In the instance that I caught this, the docker daemon has an incorrect BIP after flannel has updated its service. this is causing kubernetes containers to run and have reachability to the outside world on an unrouteable address, however any cross pod communication or even communication from the master to the worker node is impossible.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809390.
