### ISSUE TITLE
Incorrect test.yaml value

### ISSUE THREAD

**Issue by seman** [juju-solutions/charm-flannel#15]
Bundletester is not able to load test.yaml file of this charm. I think this [line](https://github.com/juju-solutions/charm-flannel/blob/master/tests/tests.yaml#L1) should be updated to the following. 

`tests: "[*]"`

**Comment by marcoceppi** [comment]
@bcsaller does this sound right to you?

**Comment by chuckbutler** [comment]
Nope @seman was right, the string is clearly quoted in the example on the bundletester readme

https://github.com/juju-solutions/bundletester

**Comment by marcoceppi** [comment]
I wasn't sure if it was a REGEX or a YAML list of regular expressions, thanks!

**Comment by chuckbutler** [comment]
I think its just a directory glob pattern... if that counts as regex.
