### ISSUE TITLE
juju remove-application cleanup not complete

### ISSUE THREAD

**Issue by SaMnCo** [juju-solutions/charm-flannel#19]
running ```juju remove-application flannel``` does not cleanup everything

* /etc/ssl/flannel still contains all certs
* /var/run/flannel/subnet.env still there
* /lib/systemd/system/flannel.service still there (but the link in /etc/systemd/system is removed)
* the flannel interface is still up & running after removal (```ip link set flannel.1 down && ip link delete flannel.1 ``` not run)

**Comment by chuckbutler** [comment]
https://github.com/juju-solutions/layer-docker/pull/92

and 

 https://github.com/juju-solutions/charm-flannel/pull/20

and 

 https://github.com/juju-solutions/interface-sdn-plugin/pull/4

should clean this issue up. This will go out with this weeks / next weeks release of our k8s bundle. Thanks for reporting this one @SaMnCo
