### ISSUE TITLE
Flannel Resources for PPC64le (Docs Needed)

### ISSUE THREAD

**Issue by kenhill** [juju-solutions/charm-flannel#30]
I am trying to deploy the kubernetes-core bundle on a mix cluster with amd64 and ppc64le nodes. I was able to create ppc64le resources for kubernetes-worker, but do not understand where to find the source for all the flannel resource binaries. 

Is there a separate repository that host the source and build instructions for flannel resources?

**Comment by Cynerva** [comment]
@kenhill Here's the script we use to build the flannel resource: https://github.com/juju-solutions/kubernetes-jenkins/blob/master/repackage-flannel.sh

In short, we are repackaging the following:
- flanneld: https://github.com/coreos/flannel/releases
- etcdctl: https://github.com/coreos/etcd/releases
- flannel, bridge, host-local: https://github.com/containernetworking/cni/releases

**Comment by kenhill** [comment]
@Cynerva Thank you for your prompt response. It would be helpful to add this information to the  `Alternate deployment methods` section of the kubernetes-core README

**Comment by chuckbutler** [comment]
Reopening so we have an indicator that this needs to be documented.

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809392.
