### ISSUE TITLE
How to conigure Flannel to use IPSEC

### ISSUE THREAD

**Issue by ade90036** [juju-solutions/charm-flannel#43]
Hi all, 

Now that flannel supports [IPSEC](https://github.com/coreos/flannel/blob/master/Documentation/backends.md#ipsec), is there a way that i configure this in the charm?

IPSEC provides **end-to-end encryption** which is often required for financial application. 

Regards

ade

**Comment by Cynerva** [comment]
Hi @ade90036,

It is not currently possible to configure the flannel charm to use the IPSEC backend. The charm hard-codes the backend to vxlan, here: https://github.com/juju-solutions/charm-flannel/blob/54b796be0f00cc98285d3587d040d41bc9f82c66/reactive/flannel.py#L167

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809394.
