### ISSUE TITLE
Incorrect flannel version in old charm

### ISSUE THREAD

**Issue by Adriien-M** [juju-solutions/charm-flannel#48]
Today we tried to clone our kubernetes production environnement (which is currently working).
However, Flannel fails to start, it throws a segmentation violation error (probably related to this issue coreos/flannel#977)

Indeed, when we compare the flannel version for the exact same charm (revision 35) we have the version 0.9.1 in production whereas the version in cloned environnement is 0.10.0.
![image](https://user-images.githubusercontent.com/927834/45968136-4ac22200-c030-11e8-80aa-83587065db75.png)
![image](https://user-images.githubusercontent.com/927834/45967752-421d1c00-c02f-11e8-89bb-48eaa528b660.png)

How is it possible that the flannel version changed in an old charm?
How can we fix it because it is impossible currently to launch flannel because of the go version?

**Comment by Adriien-M** [comment]
Thanks it is working now, I didn't know this concept of resources versionning.

Before to close the issue, is it possible to run the last flannel version (v0.10.0) in juju without get the segment violation error (coreos/flannel#977)?

**Comment by Cynerva** [comment]
> Before to close the issue, is it possible to run the last flannel version (v0.10.0) in juju without get the segment violation error (coreos/flannel#977)?

Typically yes - we haven't encountered this in testing, and I think you're the first user to report it.

Are you able to reproduce this with the latest stable flannel charm (rev 81)?

**Comment by tvansteenburgh** [comment]
Issue moved to https://bugs.launchpad.net/bugs/1809395.
